Add debugging to Arduino code
adafruit/Adafruit_TinyUSB_Arduino pull request #111
Opened 2021-07-21 01:09 UTC by WestfW

While TinyUSB in general has very good logging capabilities, the Arduino-specific code will silently fail under a number of circumstances.  This PR adds some logging to at least a couple of those.

It also makes two "logic" changes:
1) Define CFG_TUD_EP_MAX as 8 in src/arduino/ports/samd/tusb_config_samd.h
2) Take a failure return slightly earlier in Adafruit_USBD_Device::addInterface() if the number of endpoints exceeds the max.

2021-07-21 02:34 UTC, WestfW commented
Huh.  CFG_TUD_EP_MAX doesn't have a default definition in any of the typical .h files.  Instead, it checks buried down in device/usbd.c, so it's not currently defined for the non-SAMD platforms. :-(  (Causing the build failures)
```
../device/usbd.c:40:#ifndef CFG_TUD_EP_MAX
../device/usbd.c:41:#define CFG_TUD_EP_MAX          9
```

Shouldn't the default value be defined in tusb_option.h with the rest of the CFG parameters?

2021-07-21 04:51 UTC, hathach requested changes
Thank you very much for the PR, there is an on-going patch to tinyusb to better log with off limit endpoint number. These check should be dropped here to prevent duplication.

2021-07-21 04:51 UTC, hathach commented on src/arduino/Adafruit_USBD_Device.cpp
> +      }
this error log will be printed by tinyusb stack later on, I am working on tthat patch just now. Would you mind removing these.

2021-07-21 04:51 UTC, hathach commented on src/arduino/ports/samd/tusb_config_samd.h
> +#define CFG_TUD_EP_MAX 8
same as above, there is a upcoming patch to address these endpoint number. Please revert it.

2021-07-21 18:04 UTC, hathach approved these changes
superb !! Look good now. 

FYI, the work in progress is merged in tinyusb stack https://github.com/hathach/tinyusb/pull/975

PS: look like you have issue with clang. please run `clang-format -i src/arduino/*` and commit changes to fix it.

2021-09-13 12:03 UTC, hathach commented
Closed due to lack of response from user. And I can’t push to the fork

2021-09-13 12:03 UTC, closed without merging