rough fix for linux serial clients hanging while talking to nrf52 cdcserial
adafruit/Adafruit_TinyUSB_Arduino pull request #122
Opened 2021-08-15 17:31 UTC by geeksville

Hi, 

Disclaimer: I'm not sure if this is the cleanest possible fix for the problem (because I admittedly haven't looked through your entire spiffy lib in detail).  But I wanted to report the problem and the fix I made and have now tested on a number of devices.  Any feedback would be appreciated...

Problem statement:
Sometimes characters written from the nrf52 pseudo serial device to a linux
host would stop showing up on the linux app side.  This occurred randomly
but typically within a few minutes after starting a session.

The reading from linux
would remain 'hung' until you type a character on the linux side (thus
doing a new write TOWARDS the nrf52).

Theory: it seemed like something was getting hung on the linux side waiting
on a response to a read.  This led me to this code.  If I changed the code
to always send a response to any read from ep_in (rather than opting to not
send a response at all in some circumstances), "screen" apps stopped hanging.

Notes:
* problem reproducable with 'screen /dev/ttyACM0 921600' or other serial
clients (I initially used the meshtastic-python app)
* It is a _long_ time since I've messed with USB code and my analysis is
probably pretty sloppy here.  But I wanted it report it upstream in case
it is useful for others.  If there is a better fix for this problem (likely)
I'd love to change to it.

'fixes' https://github.com/meshtastic/Meshtastic-device/issues/838

2021-08-16 06:01 UTC, hathach requested changes
Although it may fix the symptom you have, it is not a correct "fix". We only need to send 0len packet when sending multiple of 64 bytes.  When there is no new data to send, NACK is right way to response. 

It is probably your terminal software that has a special needs, I am willing to help if you open an issue for this with precise instruction to reproduce along with all the software with version used.

2021-08-16 18:55 UTC, geeksville commented
Hi @hathach thank you for your reply, this behavior was seen in the following:

* Ubuntu 20.10 'screen' command (screen /dev/ttyACM0 921600)
* Ubuntu 20.10 'minicom' command
* and my custom (but fairly heavily used by others) 'meshtastic-python' tool (available on all platforms via pip install meshtastic-python).  I'm familar with the internal structure of this tool, it just has two threads - one blocked on reads from the cdc device (and when a character arrive it prints/processes it) and one that occasionally does writes to the cdc device.

> It is probably your terminal software that has a special needs

Given that the behavior is the same on three userspace tools, two of which are **super** mature and highly used.  I suspect the problem is either on the nrf52 device side or the linux kernel cdc-acm driver.  But the cdc-acm driver is also very mature and used with many other cdc USB devices where this issue does not show up.

2021-08-16 19:00 UTC, geeksville commented
> When there is no new data to send, NACK is right way to response.

Hmm - where in the cdc_device code is it sending the NACK response?  I can look around there to confirm that is happening.

2021-08-17 04:49 UTC, hathach commented
Thank you for providing more information however there is still not enough to reproduce the issue. I would need the board, bsp version, sketch and step to reproduce, also some of the log (dmesg, stack log etc ..). Would you mind opening an bug issue (copy existing text over), we could discuss there further. I will close this PR since the modification is more of a hack than a fix, and would not be accepted.

> Hmm - where in the cdc_device code is it sending the NACK response? I can look around there to confirm that is happening.

If you don't send anything, hw controller will response with NAK.

PS: It could be the work of modem manager in Linux, try to disable it either by stopping its server or using udev rule to see if that is the case.

2021-08-17 04:49 UTC, closed without merging

2021-08-17 20:53 UTC, geeksville commented
Thanks - I have had modemmanager uninstalled for a long time.

Ok - I'll send in an issue someday.

On Mon, Aug 16, 2021 at 9:50 PM Ha Thach ***@***.***> wrote:

> Thank you for providing more information however there is still not enough
> to reproduce the issue. I would need the board, bsp version, sketch and
> step to reproduce, also some of the log (dmesg, stack log etc ..). Would
> you mind opening an bug issue (copy existing text over), we could discuss
> there further. I will close this PR since the modification is more of a
> hack than a fix, and would not be accepted.
>
> Hmm - where in the cdc_device code is it sending the NACK response? I can
> look around there to confirm that is happening.
>
> If you don't send anything, hw controller will response with NAK.
>
> PS: It could be the work of modem manager in Linux, try to disable it
> either by stopping its server or using udev rule to see if that is the case.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/adafruit/Adafruit_TinyUSB_Arduino/pull/122#issuecomment-899990849>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABXB2OSDYMGDWIPYABNEJ3T5HS7XANCNFSM5CGMCAIA>
> .
>

2021-08-17 20:57 UTC, geeksville commented
@hathach btw - I just took a look at exisiting issues and:

https://github.com/adafruit/Adafruit_TinyUSB_Arduino/issues/57

I bet could have been the same thing.  My devices also appeared to "hang" after printing longish strings.  But they would unhang if a character was sent from the host to the nrf52 device.

best wishes to you and your project.

2021-08-18 05:38 UTC, hathach commented
thanks for your kind words, that is webusb which use different driver than cdc both in device firmware and host driver.